### ISSUE TITLE
call CRISPR spacers  from user's own genomes and link virus to host

### ISSUE THREAD

**Issue by liupfskygre** [edzuf/CrisprOpenDB#12]
Hi,
   I want to call CRISPR spacer from my own bacteria genomes and blast them against my own virus dataset. I am wondering if CrisprOpenDB tool kit cold this in few lines. 

thanks!

**Comment by plpla** [comment]
Hello @liupfskygre ,
right now the tools does not allow to do this kind of process in a very simple way but we are working on something. I don't know when it will be ready.
The construction of the database relies on finding the spacers with an external tool (CRISPRdetect) and linking these to the taxonomy of the different bacteria. If you have this information for your bacteria, we can help you build your own spacer database to be used with our tool to analyse your viruses.

**Comment by liupfskygre** [comment]
thanks. but the DB is awesome!!!
