### ISSUE TITLE
how can I get the host information after running a local blast with the spacer db

### ISSUE THREAD

**Issue by linxingchen** [edzuf/CrisprOpenDB#13]
Dear author(s),

Could you please let me know how can I get the information of the host by having a blast spacer hit, for example, LSRS01000003? What should I do? Thanks.

Best,
Lin-Xing Chen
UC Berkeley

**Comment by plpla** [comment]
Hello @linxingchen,
there is two ways to analyze and find the host. First is using the command line tool available through this repo.
The second option is to run blast manually and use the Python librairie available in the repo to run/extract the info manually. I highly recommend the first option as it is a lot easier.

Let us know if you can't make it work.
