### ISSUE TITLE
BLAST Database error: Error pre-fetching sequence data

### ISSUE THREAD

**Issue by JSSaini** [edzuf/CrisprOpenDB#15]
Hi, I even try to give an absolute path to the database but keep on getting this error. 

python CL_Interface.py -i viral_population_11m_95-80.fna  -a blast -b /home/users/s/saini7/scratch/MS3/CrisprOpenDB/CrisprOpenDB/SpacersDB/SpacersDB

BLAST Database error: Error pre-fetching sequence data
No hits found. Sorry!

Any suggestions on workaround would be helpful.

**Comment by plpla** [comment]
Hello @JSSaini, 
sorry for not coming back to you sooner! Have you solved this?
