### ISSUE TITLE
How to get the spacer database?

### ISSUE THREAD

**Issue by hannet91** [edzuf/CrisprOpenDB#16]
Hi 
I want to use this method to analysis the viral hosts, however, ccouldn't download the spacer database in below link (http://crispr.genome.ulaval.ca/ or http://crispr.genome.ulaval.ca/dash/PhageHostIdentifier_DBfiles.zip). Could you tell me how to get this database in China. Thanks for you help.

Liao

**Comment by plpla** [comment]
Hello @hannet91,
the second link you provided seems to work on my computer if I paste it in the URL bar.
It should also work with a wget command. If the issue is your location (China), can you try to pass through a VPN?
