### ISSUE TITLE
sqlite database link broken

### ISSUE THREAD

**Issue by ryneches** [edzuf/CrisprOpenDB#7]
Not a software bug, but I'm getting an internal server error trying to download the sqlite database : http://crispr.genome.ulaval.ca/dash/PhageHostIdentifier_DBfiles.zip

**Comment by plpla** [comment]
Hello @ryneches,
Thanks for reporting the issue. I'll look into it.

**Comment by plpla** [comment]
@ryneches Everything should work now! Let me know if you have more issues.

**Comment by SergeyBaikal** [comment]
The link doesn't work. Can you post on an alternative resource?
